name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'tdawatson'
          reponame: 'bad-news-beers'
          token: ${{ secrets.GITHUB_TOKEN }}
          cname: 'badnewsbeers.net'
